## ----------------------------------------------------------------------------
## ..:: NGINX Plus Deployment ::..
## ----------------------------------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-ingress-banking-app
  namespace: banking-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-ingress-banking-app
  template:
    metadata:
      labels:
        app: nginx-ingress-banking-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9113"
    spec:
      serviceAccountName: nginx-ingress
      containers:
      - image: registry.f5-udf.com:5000/nginx-plus-ingress:1.11.1
        imagePullPolicy: Always
        name: nginx-plus-ingress
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        - name: readiness-port
          containerPort: 8081
        - name: prometheus
          containerPort: 9113
        readinessProbe:
          httpGet:
            path: /nginx-ready
            port: readiness-port
          periodSeconds: 1
        securityContext:
          allowPrivilegeEscalation: true
          runAsUser: 101 #nginx
          capabilities:
            drop:
            - ALL
            add:
            - NET_BIND_SERVICE
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        args:
          - -nginx-plus
          - -nginx-configmaps=$(POD_NAMESPACE)/nginx-config
          - -default-server-tls-secret=$(POD_NAMESPACE)/default-server-secret
          - -watch-namespace=banking-app
          - -v=3 # Enables extensive logging. Useful for troubleshooting.
          - -report-ingress-status
          - -nginx-status-allow-cidrs=10.0.0.0/8
         #- -external-service=nginx-ingress
          - -enable-prometheus-metrics
         #- -global-configuration=$(POD_NAMESPACE)/nginx-configuration
---
## ----------------------------------------------------------------------------
## ..:: NGINX Plus ClusterIP Service - Port 80 ::..
## ----------------------------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: banking-app-kic-80
  namespace: banking-app
  labels:
    app: nginx-ingress-banking-app
    cis.f5.com/as3-tenant: banking-app
    cis.f5.com/as3-app: banking-app-kic
    cis.f5.com/as3-pool: banking-app-kic-pool-80
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: nginx-ingress-banking-app
---
## ----------------------------------------------------------------------------
## ..:: NGINX Plus ClusterIP Service - Port 443 ::..
## ----------------------------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: banking-app-kic-443
  namespace: banking-app
  labels:
    app: nginx-ingress
    cis.f5.com/as3-tenant: banking-app
    cis.f5.com/as3-app: banking-app-kic
    cis.f5.com/as3-pool: banking-app-kic-pool-443
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 443
    targetPort: 443
    protocol: TCP
  selector:
    app: nginx-ingress-banking-app
---
## ----------------------------------------------------------------------------
## ..:: NGINX Plus ClusterIP Service - Port 8080 ::..
## ----------------------------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: banking-app-kic-8080
  namespace: banking-app
  labels:
    app: nginx-ingress
    cis.f5.com/as3-tenant: banking-app
    cis.f5.com/as3-app: banking-app-kic
    cis.f5.com/as3-pool: banking-app-kic-pool-8080
spec:
  type: ClusterIP
  ports:
  - name: http-8080
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: nginx-ingress-banking-app
