## ..:: NGINX ConfigMap for k8s-bigip-ctlr (AS3) ::..
## ----------------------------------------------------------------------------
kind: ConfigMap
apiVersion: v1
metadata:
  name: f5-to-k8s-performance-monitoring
  namespace: performance-monitoring
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
        "class": "AS3",
        "declaration": {
            "class": "ADC",
            "schemaVersion": "3.13.0",
            "id": "urn:uuid:33045210-3ab8-4636-9b2a-c98d22ab915d",
            "label": "http",
            "remark": "A1 Template",
            "performance-monitoring": {
                "class": "Tenant",
                "prometheus-9090": {
                    "class": "Application",
                    "template": "generic",
                    "prometheus-9090-vs": {
                        "class": "Service_HTTP",
                        "remark": "prometheus-9090",
                        "virtualAddresses": [
                            "10.1.10.105"
                        ],
                        "pool": "prometheus-pool-9090"
                    },
                    "prometheus-pool-9090": {
                        "class": "Pool",
                        "monitors": [
                            "http"
                        ],
                        "members": [
                            {
                                "servicePort": 9090,
                                "serverAddresses": []
                            }
                        ]
                    }
                }                            
            }
        }
    }