apiVersion: v1
kind: PersistentVolume
metadata:
  name: blog-apps-nfs-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: blog-apps-nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /home/ubuntu/dockerhost-storage/nfs-storage
    server: 10.1.20.20
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blog-apps-pvc
  namespace: blog-apps
spec:
  storageClassName: blog-apps-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
