## ..:: NGINX ConfigMap for k8s-bigip-ctlr (AS3) ::..
## ----------------------------------------------------------------------------
kind: ConfigMap
apiVersion: v1
metadata:
  name: f5-to-nginx-ingress
  namespace: blog-apps
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
        "class": "AS3",
        "declaration": {
            "class": "ADC",
            "schemaVersion": "3.13.0",
            "id": "urn:uuid:33045210-3ab8-4636-9b2a-c98d22ab915d",
            "label": "http",
            "remark": "A1 Template",
            "blog-apps": {
                "class": "Tenant",
                "blog-apps-kic-80": {
                    "class": "Application",
                    "template": "generic",
                    "blog-apps-kic-80-vs": {
                        "class": "Service_HTTP",
                        "remark": "blog-apps-kic-80",
                        "virtualAddresses": [
                            "10.1.10.102"
                        ],
                        "pool": "blog-apps-kic-pool-80"
                    },
                    "blog-apps-kic-pool-80": {
                        "class": "Pool",
                        "monitors": [
                            "tcp"
                        ],
                        "members": [
                            {
                                "servicePort": 80,
                                "serverAddresses": []
                            }
                        ]
                    }
                },
                "blog-apps-kic-8080": {
                    "class": "Application",
                    "template": "generic",
                    "blog-apps-kic-8080-vs": {
                        "class": "Service_HTTP",
                        "remark": "blog-apps-kic-8080",
                        "virtualPort": 8080,
                        "virtualAddresses": [
                            "10.1.10.102"
                        ],
                        "pool": "blog-apps-kic-pool-8080"
                    },
                    "blog-apps-kic-pool-8080": {
                        "class": "Pool",
                        "monitors": [
                            "http"
                        ],
                        "members": [
                            {
                                "servicePort": 8080,
                                "serverAddresses": []
                            }
                        ]
                    }
                },
                "blog-apps-kic-443": {
                    "class": "Application",
                    "template": "generic",
                    "blog-apps-kic-443-vs": {
                        "class": "Service_TCP",
                        "remark": "blog-apps-kic-443",
                        "virtualAddresses": [
                            "10.1.10.102"
                        ],
                        "virtualPort": 443,
                        "pool": "blog-apps-kic-pool-443"
                    },
                    "blog-apps-kic-pool-443": {
                        "class": "Pool",
                        "monitors": [
                            "tcp"
                        ],
                        "members": [
                            {
                                "servicePort": 443,
                                "serverAddresses": []
                            }
                        ]
                    }
                },
                "blog-apps-kic-9113": {
                    "class": "Application",
                    "template": "generic",
                    "blog-apps-kic-9113-vs": {
                        "class": "Service_TCP",
                        "remark": "blog-apps-kic-9113",
                        "virtualAddresses": [
                            "10.1.10.102"
                        ],
                        "virtualPort": 9113,
                        "pool": "blog-apps-kic-pool-9113"
                    },
                    "blog-apps-kic-pool-9113": {
                        "class": "Pool",
                        "monitors": [
                            "tcp"
                        ],
                        "members": [
                            {
                                "servicePort": 9113,
                                "serverAddresses": []
                            }
                        ]
                    }
                }
            }
        }
    }
