## ----------------------------------------------------------------------------
## ..:: infra-server installation ::..
## ----------------------------------------------------------------------------

- hosts: infra-server
  remote_user: root
  tasks:

    ## Configure and Deploy Services in "blog-apps" namespace


    - name: Undeploying MYSQL DB Server for blog-apps services
      become: true
      become_user: ubuntu
      command: /bin/bash -c "export KUBECONFIG=/home/ubuntu/.kube/config-k8s ; kubectl delete -f ~/k8s-manifests/blog-apps/0.namespace-preparation/5.mysql.yaml"

    - name: Undeploying BIG-IP Controller Config Map 
      become: true
      become_user: ubuntu
      command: /bin/bash -c "export KUBECONFIG=/home/ubuntu/.kube/config-k8s ; kubectl delete -f ~/k8s-manifests/blog-apps/0.namespace-preparation/4.bigip-ctlr-configMap.yaml"

    - name: Undeploying NGINX Plus Ingress Controller PODs and Services
      become: true
      become_user: ubuntu
      command: /bin/bash -c "export KUBECONFIG=/home/ubuntu/.kube/config-k8s ; kubectl delete -f ~/k8s-manifests/blog-apps/0.namespace-preparation/3.nplus-nap-blog-apps.yaml"

    - name: Undeploying Common NGINX Plus resources
      become: true
      become_user: ubuntu
      command: /bin/bash -c "export KUBECONFIG=/home/ubuntu/.kube/config-k8s ; kubectl delete -f ~/k8s-manifests/blog-apps/0.namespace-preparation/2.nginx-blog-apps.yaml"

    - name: Undeploying PV / PVC foro persistent flie storage
      become: true
      become_user: ubuntu
      command: /bin/bash -c "export KUBECONFIG=/home/ubuntu/.kube/config-k8s ; kubectl delete -f ~/k8s-manifests/blog-apps/0.namespace-preparation/1.nfs-pv-pvc.yaml"

