## ----------------------------------------------------------------------------
## ..:: Arcadia Banking App Anisble playbook ::..
## ----------------------------------------------------------------------------

- hosts: infra-server
  remote_user: root
  tasks:

    ## Deploy Arcadia PODs

    - name: Deploying main application
      become: true
      become_user: ubuntu
      command: /bin/bash -c "export KUBECONFIG=/home/ubuntu/.kube/config-k8s ; kubectl apply -f ~/k8s-manifests/banking-apps/arcadia/2.main.yaml"

    - name: Deploying backend application
      become: true
      become_user: ubuntu
      command: /bin/bash -c "export KUBECONFIG=/home/ubuntu/.kube/config-k8s ; kubectl apply -f ~/k8s-manifests/banking-apps/arcadia/3.backend.yaml"

    - name: Deploying app2 application
      become: true
      become_user: ubuntu
      command: /bin/bash -c "export KUBECONFIG=/home/ubuntu/.kube/config-k8s ; kubectl apply -f ~/k8s-manifests/banking-apps/arcadia/4.app2.yaml"

    - name: Deploying app3 application
      become: true
      become_user: ubuntu
      command: /bin/bash -c "export KUBECONFIG=/home/ubuntu/.kube/config-k8s ; kubectl apply -f ~/k8s-manifests/banking-apps/arcadia/5.app3.yaml"

    - name: Deploying arcadia VS for KIC
      become: true
      become_user: ubuntu
      command: /bin/bash -c "export KUBECONFIG=/home/ubuntu/.kube/config-k8s ; kubectl apply -f ~/k8s-manifests/banking-apps/arcadia/6.arcadia-vs.yaml"