## ----------------------------------------------------------------------------
## ..:: Arcadia Banking App Anisble playbook ::..
## ----------------------------------------------------------------------------

- hosts: infra-server
  remote_user: root
  tasks:

    ## Deploy Arcadia PODs

    - name: undeploying banking-apps k8s-bigip-ctlr configMap
      become: true
      become_user: ubuntu
      command: /bin/bash -c "export KUBECONFIG=/home/ubuntu/.kube/config-k8s ; kubectl delete -f ~/k8s-manifests/banking-apps/0.namespace-preparation/4.bigip-ctlr-configMap.yaml"

    - name: undeploying banking-apps NGINX Plus Kubernetes Ingress Controller
      become: true
      become_user: ubuntu
      command: /bin/bash -c "export KUBECONFIG=/home/ubuntu/.kube/config-k8s ; kubectl delete -f ~/k8s-manifests/banking-apps/0.namespace-preparation/3.nplus-nap.yaml"

    - name: undeploying banking-apps NGINX Plus Common Stuff
      become: true
      become_user: ubuntu
      command: /bin/bash -c "export KUBECONFIG=/home/ubuntu/.kube/config-k8s ; kubectl delete -f ~/k8s-manifests/banking-apps/0.namespace-preparation/2.nginx-plus-common.yaml"
