## ----------------------------------------------------------------------------
## ..:: Online-BOutique App Anisble playbook ::..
## ----------------------------------------------------------------------------

- hosts: infra-server
  remote_user: root
  tasks:

    ## Undeploy Online Boutique Namespace / NGINX+ KIC / F5 ConfigMap

    - name: Undeploying online-boutique k8s-bigip-ctlr configMap
      become: true
      become_user: ubuntu
      command: /bin/bash -c "export KUBECONFIG=/home/ubuntu/.kube/config-k8s ; kubectl delete -f ~/k8s-manifests/online-boutique/0.namespace-preparation/4.bigip-ctlr-configMap.yaml"

    - name: Undeploying online-boutique NGINX Plus Kubernetes Ingress Controller
      become: true
      become_user: ubuntu
      command: /bin/bash -c "export KUBECONFIG=/home/ubuntu/.kube/config-k8s ; kubectl delete -f ~/k8s-manifests/online-boutique/0.namespace-preparation/3.nplus-nap.yaml"

    - name: Undeploying online-boutique NGINX Plus Common Stuff
      become: true
      become_user: ubuntu
      command: /bin/bash -c "export KUBECONFIG=/home/ubuntu/.kube/config-k8s ; kubectl delete -f ~/k8s-manifests/online-boutique/0.namespace-preparation/2.nginx-plus-common.yaml"
