## ----------------------------------------------------------------------------
## ..:: Online-Butique [Aspen Mesh Eanbled] App Anisble playbook ::..
## ----------------------------------------------------------------------------

- hosts: infra-server
  remote_user: root
  tasks:

    ## Deploy Online Boutique - Aspen Mesh Enabled

    - name: Deploying online-boutique-am namespace
      become: true
      become_user: ubuntu
      command: /bin/bash -c "export KUBECONFIG=/home/ubuntu/.kube/config-k8s ; kubectl apply -f ~/k8s-manifests/online-boutique-am/0.namespace.yaml"

    - name: Deploying Online Boutique Application
      become: true
      become_user: ubuntu
      command: /bin/bash -c "export KUBECONFIG=/home/ubuntu/.kube/config-k8s ; kubectl apply -f ~/k8s-manifests/online-boutique-am/1.kubernetes-manifests.yaml"

    - name: Deploying Online Boutique Istio Ingress Config
      become: true
      become_user: ubuntu
      command: /bin/bash -c "export KUBECONFIG=/home/ubuntu/.kube/config-k8s ; kubectl apply -f ~/k8s-manifests/online-boutique-am/2.frontend-gateway.yaml"
