## ----------------------------------------------------------------------------
## ..:: Online-Butique [Aspen Mesh Eanbled] App Anisble playbook ::..
## ----------------------------------------------------------------------------

- hosts: infra-server
  remote_user: root
  tasks:

    ## Deploy Online Boutique - Aspen Mesh Enabled

    - name: Uneploying Online Boutique Istio Ingress Config
      become: true
      become_user: ubuntu
      command: /bin/bash -c "export KUBECONFIG=/home/ubuntu/.kube/config-k8s ; kubectl delete -f ~/k8s-manifests/online-boutique/2.frontend-gateway.yaml"

    - name: Uneploying Online Boutique Application
      become: true
      become_user: ubuntu
      command: /bin/bash -c "export KUBECONFIG=/home/ubuntu/.kube/config-k8s ; kubectl delete -f ~/k8s-manifests/online-boutique/1.kubernetes-manifests.yaml"

    - name: Uneploying online-boutique-am namespace
      become: true
      become_user: ubuntu
      command: /bin/bash -c "export KUBECONFIG=/home/ubuntu/.kube/config-k8s ; kubectl delete -f ~/k8s-manifests/online-boutique/0.namespace.yaml"

