## ..:: NGINX ConfigMap for k8s-bigip-ctlr (AS3) ::..
## ----------------------------------------------------------------------------
kind: ConfigMap
apiVersion: v1
metadata:
  name: f5-to-nginx-ingress
  namespace: performance-monitoring
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
        "class": "AS3",
        "declaration": {
            "class": "ADC",
            "schemaVersion": "3.13.0",
            "id": "urn:uuid:33045210-3ab8-4636-9b2a-c98d22ab915d",
            "label": "http",
            "remark": "A1 Template",
            "performance-monitoring": {
                "class": "Tenant",
                "performance-monitoring-kic-80": {
                    "class": "Application",
                    "template": "generic",
                    "performance-monitoring-kic-80-vs": {
                        "class": "Service_HTTP",
                        "remark": "performance-monitoring-kic-80",
                        "virtualAddresses": [
                            "10.1.10.105"
                        ],
                        "pool": "performance-monitoring-kic-pool-80"
                    },
                    "performance-monitoring-kic-pool-80": {
                        "class": "Pool",
                        "monitors": [
                            "tcp"
                        ],
                        "members": [
                            {
                                "servicePort": 80,
                                "serverAddresses": []
                            }
                        ]
                    }
                },
                "performance-monitoring-kic-443": {
                    "class": "Application",
                    "template": "generic",
                    "performance-monitoring-kic-443-vs": {
                        "class": "Service_TCP",
                        "remark": "performance-monitoring-kic-443",
                        "virtualAddresses": [
                            "10.1.10.105"
                        ],
                        "virtualPort": 443,
                        "pool": "performance-monitoring-kic-pool-443"
                    },
                    "performance-monitoring-kic-pool-443": {
                        "class": "Pool",
                        "monitors": [
                            "tcp"
                        ],
                        "members": [
                            {
                                "servicePort": 443,
                                "serverAddresses": []
                            }
                        ]
                    }
                }
            }
        }
    }
