## ----------------------------------------------------------------------------
## ..:: NGINX KIC VS Configuration for Hackazon ::..
##-----------------------------------------------------------------------------
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: hackazon-ingress
  namespace: nap-e-commerce
  annotations:
    kubernetes.io/ingress.class: "nginx"
    appprotect.f5.com/app-protect-policy: "ingress-services/nginx-policy"
    appprotect.f5.com/app-protect-enable: "True"
    appprotect.f5.com/app-protect-security-log-enable: "True"
    appprotect.f5.com/app-protect-security-log: "ingress-services/logconf"
    appprotect.f5.com/app-protect-security-log-destination: "syslog:server=10.1.10.207:5144"
spec:
    rules:
    - host: shop.f5-udf.com
      http:
        paths:
          - path: /
            backend:
               serviceName: hackazon
               servicePort: 80