apiVersion: v1
kind: PersistentVolume
metadata:
  name: nap-e-commerce-nfs-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nap-e-commerce-nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /home/ubuntu/dockerhost-storage/nfs-storage
    server: 10.1.20.20
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nap-e-commerce-pvc
  namespace: nap-e-commerce
spec:
  storageClassName: nap-e-commerce-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
