## ----------------------------------------------------------------------------
## ..:: Mysql POD / Service Configuration ::..
##-----------------------------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: mysql-hackazon
  namespace: test-ns
spec:
  ports:
  - port: 3306
  selector:
    app: mysql-hackazon
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-hackazon
  namespace: test-ns
spec:
  selector:
    matchLabels:
      app: mysql-hackazon
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-hackazon
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: Default1234!
        ports:
        - containerPort: 3306
          name: mysql-hackazon
        volumeMounts:
        - name: test-ns-persistent-storage
          mountPath: /var/lib/mysql
          subPath: test-ns/mysql
      volumes:
      - name: test-ns-persistent-storage
        persistentVolumeClaim:
          claimName: test-ns-pvc
